# Do NOT update manually; changes here will be overwritten by Copier
_commit: 089da8d
_src_path: https://github.com/it-projects-llc/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: IT-Projects LLC
org_slug: it-projects-llc
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: website-addons
repo_website: https://github.com/it-projects-llc/website-addons
use_pyproject_toml: true
use_ruff: true

