{
    "name": """Product swap at eCommerce""",
    "summary": """Product upgrading / changing feature for your online shop""",
    "category": "eCommerce",
    "images": ["images/banner.jpg"],
    "version": "14.0.1.0.0",
    "application": False,
    "author": "IT-Projects LLC",
    "support": "it@it-projects.info",
    "website": "https://github.com/it-projects-llc/website-addons",
    "license": "LGPL-3",
    "depends": ["website_sale"],
    "data": [
        "data/product.xml",
        "views/website_sale_templates.xml",
        "views/sale_order_views.xml",
    ],
    "qweb": [],
    "demo": [],
}
